version: '2'
services:
    astcore-app:
        image: astcore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@astcore-oracle:1521:astcore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=astcore-elasticsearch:9300
        ports:
            - 8080:8080
    astcore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: astcore-elasticsearch
